/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#630ed4',
        'primary-container': '#7c3aed',
        'on-primary': '#ffffff',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#d2bbff',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        secondary: '#006c44',
        'secondary-container': '#25fea8',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007147',
        'secondary-fixed': '#50ffaf',
        'secondary-fixed-dim': '#00e293',
        'on-secondary-fixed': '#002111',
        'on-secondary-fixed-variant': '#005232',
        tertiary: '#982100',
        'tertiary-container': '#c32c00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffdfd7',
        'tertiary-fixed': '#ffdad2',
        'tertiary-fixed-dim': '#ffb4a2',
        'on-tertiary-fixed': '#3c0700',
        'on-tertiary-fixed-variant': '#8a1d00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#faf8ff',
        'on-background': '#131b2e',
        surface: '#faf8ff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#4a4455',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-tint': '#732ee4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        outline: '#7b7487',
        'outline-variant': '#ccc3d8',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'DM Sans', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'DM Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
